### DISCUSSION TITLE
Updates page states

### DISCUSSION THREAD

**Discussion by hancooo** [matt8707/hass-config#106] [General]
Hi pal. 
First up, epic dashboard. Thanks. Few screenshots of my setup so far (still a lot to finish). 
Question at the bottom. 

![image](https://user-images.githubusercontent.com/20757683/195440880-c40a59f7-3454-4fbf-8847-0ed9512001ba.png)
![image](https://user-images.githubusercontent.com/20757683/195440943-2f8994e2-e9f7-4e62-8fe4-93138f1377e3.png)

I am running HA OS on a Raspberry Pi
I am struggling to figure out how you setup the states and senors for the update popup, specfically the HASS and HACS section.
Any help would be much appreciated. 

Below is your code that I am referring too:

**From the footer_updates.yaml popup**
```
      card:
        type: grid
        columns: 1
        square: false
        cards:
          - type: custom:button-card
            entity: sensor.current_version
            template: updates_hass
            variables:
              latest: sensor.docker_hub
              latest_beta: sensor.docker_hub_beta
              release_notes: sensor.hass_release_notes
              release_notes_beta: sensor.hass_release_notes_beta

          - type: custom:button-card
            entity: sensor.current_version
            name: Update HASS
            variables:
              latest: sensor.docker_hub
              latest_beta: sensor.docker_hub_beta
            tap_action:
              action: call-service
              service: browser_mod.sequence
              service_data:
                sequence:
                  - service: browser_mod.notification
                    data:
                      message: Startar watchtower...
                  - service: switch.turn_on
                    data:
                      entity_id: switch.docker_watchtower
            template: updates_hass_icon_name

          - type: custom:button-card
            entity: sensor.hacs
            variables:
              installed: sensor.hacs_installed
            template: updates_hacs

          - type: custom:button-card
            entity: sensor.hacs
            name: Open HACS
            template:
              - updates_hacs_icon_name
              - >
                [[[
                  return window.navigator.userAgent.match(/iPhone/i)
                    ? 'hacs_navigate_ios'
                    : 'hacs_iframe';
                ]]]
``` 

**From the updates.yaml button card template**
```
updates_hass:
  template:
    - updates
    - settings
  state_display: |
    [[[
      if (entity) {
          let links = new RegExp('<a href="([^"]+)"', "g"),
              installed = entity.state,
              hass_version_latest = states[variables.latest],
              hass_version_latest_beta = states[variables.latest_beta],
              hass_release_notes = states[variables.release_notes],
              hass_release_notes_beta = states[variables.release_notes_beta];

          let latest = installed.includes('b')
              ? hass_version_latest_beta.state
              : hass_version_latest.state;

          let release_notes = installed.includes('b')
              ? marked.parse(hass_release_notes.attributes.body)
              : marked.parse(hass_release_notes_beta.attributes.body);

          let subtitle = installed === latest
              ? `${variables.translate_no_updates} <b>&larr;</b> ${installed}`
              : `${ !installed.includes('.') || !latest.includes('.')
                  ? `${variables.translate_no_updates} <b>&larr;</b> ${installed}`
                  : `${installed} <b>&rarr;</b> ${latest} ${variables.translate_available} ${String.fromCodePoint("0x1f389")}` }`;

          let output = installed === latest
              ? '<ul></ul>'
              : `${ !installed.includes('.') || !latest.includes('.')
                  ? '<ul></ul>'
                  : release_notes.replace(links, '<a href="#" onclick="window.open(\'$1\')"') }`;

          return `
            <ha-icon icon="mdi:home-assistant"></ha-icon> <span class="title">Home Assistant</span><br>
            <p class="subtitle">${subtitle}</p>
            ${output}
          `;
      }
    ]]]

updates_hass_icon_name:
  template: icon_name
  icon: mdi:update
  styles:
    card:
      - opacity: >
          [[[
            return entity && (entity.state === states[variables.latest].state ||
              entity.state === states[variables.latest_beta].state)
                ? '0.3'
                : '1';
          ]]]
      - display: >
          [[[
            return entity
              ? 'flex'
              : 'none';
          ]]]

updates_hacs:
  template:
    - updates
    - settings
  state_display: |
    [[[
      if (entity) {
          let output = '',
              count = parseInt(entity.state) || 0,
              subtitle = count === 0
                  ? `${variables.translate_no_updates} <b>&larr;</b> ${states['update.hacs_update'].attributes.installed_version || ''}`
                  : `${count} ${count === 1 ? variables.translate_update_available : variables.translate_updates_available} ${String.fromCodePoint('0x1f389')}`;

          Object.keys(states).forEach(key => {
            let s = states[key],
                e = s.entity_id,
                a = s.attributes;

            if (e.includes('update.') && s.state === 'on' && a.release_url) {
                let split_url = a.release_url.split('/'),
                    name = `${split_url[3]}/${split_url[4]}`,
                    installed = states[variables.installed].attributes.repositories;

                if (installed.includes(name)) {
                    output += `<li><b><a href="#" onclick="window.open('${a.release_url}');">
                    ${name}</a></b> ${a.installed_version} <b>&rarr;</b> ${a.latest_version}</li>`
                }
            }
          });

          return `
            <ha-icon icon="hacs:hacs"></ha-icon> <span class="title">Community Store</span><br>
            <p class="subtitle">${subtitle}</p>
            <ul>${output}</ul>
          `;
      }
    ]]]

updates_hacs_icon_name:
  template: icon_name
  icon: mdi:open-in-new
  styles:
    card:
      - opacity: >
          [[[
            return entity && entity.state === '0'
                ? '0.3'
                : '1';
          ]]]
      - display: >
          [[[
            return entity && entity.state !== 'unknown'
                ? 'flex'
                : 'none';
          ]]]
```

I am just getting this. 
![image](https://user-images.githubusercontent.com/20757683/195442767-f8d7c814-9d79-4824-bba5-d201339b9507.png)

The only one I have been able to get working is the sensor.current_version
![image](https://user-images.githubusercontent.com/20757683/195442908-fdef3472-f6db-4abe-9e9a-5706f38d9106.png)
