### DISCUSSION TITLE
problem with sidebar.yaml

### DISCUSSION THREAD

**Discussion by dejongac** [matt8707/hass-config#109] [Q&A]
I tried to follow the instructions in install.md.
But when i tried to restart home assistant it gave an an error "Error loading /config/configuration.yaml: mapping values are not allowed here in "/config/sidebar.yaml", line 28, column 63.

I used the sidebar.yaml from the site.
Anyone know whats wrong?

Thanks

Albert

**Comment by matt8707** [comment]
if you changed anything in sidebar.yaml post the contents of that file else post your configuration.yaml

**Reply by matt8707** [reply]
you might want to delete this, you just leaked passwords and email

and post inside triple backticks https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Reply by dejongac** [reply]
Thanks i had a version without the mail/password but apparently copier the wrong one.

**Comment by dejongac** [comment]
Nothing changed in my configuration file except i added template: !include sidebar.yaml
The configuration checker in HA also points to the sidebar.yaml 
pointing to line 28, column 63     <meta name="optimizely-datafile" content="{&quot;groups&quot;: 

here is the configuration.yaml

# Configure a default setup of Home Assis tant (frontend, api, etc)
default_config:

```
customize: !include customize.yaml
# packages: !include_dir_named packages/
automation: !include automations.yaml
frontend: !include themes.yaml
template: !include sidebar.yaml
```

```
lovelace:
  resources: !include lovelace/resources/resources.yaml

  dashboards:
    sidebar-dashboard:
      mode: yaml
      filename: lovelace/ui-lovelace.yaml
      title: Sidebar
      icon: mdi:tablet
      show_in_sidebar: true
```
  
```
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://rawgit.com/james-fry/home-assistant-mdi/master/home-assistant-mdi.html
```

```
# Text to speech
tts:
- platform: google_translate
```  

sensor:
  ``` 
  # Formula 1
  - platform: formulaone_api
```

```
  # Date & Time
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
```

```
  - platform: template
    sensors:
      week_day:
        value_template: "{{ now().strftime('%A')}}"
      current_date:
        value_template: "{{ now().strftime('%d')}} {{ now().strftime('%B')}} {{ now().strftime('%Y')}}"
```

```    
  # Brandstofprijzen
  # Euro95
  - platform: scrape
    name: Euro95 Advies
    resource: "https://www.unitedconsumers.com/brandstofprijzen"
    select: ".table div:nth-of-type(2) div:nth-of-type(3)"
    value_template: "{{ value |replace('€', '') |replace(',', '.') |round(3) }}"
    scan_interval: 3600 # be nice; once per hour only

  - platform: scrape
    name: Euro95 Tinq Concordiaweg
    resource: "https://www.tinq.nl/tankstations/gorinchem-concordiaweg#default"
    select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
    value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
    scan_interval: 3600 # be nice; once per hour only
    
  - platform: scrape
    resource: "https://tankservice.app-it-up.com/Tankservice/v2/places/3337.png?lang=nl"
    name: Euro95 Argos.stationseweg
    select: ".price"
    value_template: "{{ value.split(' ')[0].replace(',', '.') | float }}"
    scan_interval: 3600
  
  # Diesel
  - platform: scrape
    name: Diesel Advies
    resource: "https://www.unitedconsumers.com/brandstofprijzen"
    select: ".table div:nth-of-type(2) div:nth-of-type(3)"
    value_template: "{{ value |replace('€', '') |replace(',', '.') |round(3) }}"
    scan_interval: 3600 # be nice; once per hour only

  - platform: scrape
    name: Diesel Tinq Concordiaweg
    resource: "https://www.tinq.nl/tankstations/gorinchem-concordiaweg#default"
    select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
    value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
    scan_interval: 3600 # be nice; once per hour only
    
  - platform: scrape
    resource: "https://tankservice.app-it-up.com/Tankservice/v2/places/3337.png?lang=nl"
    name: Diesel Argos stationsweg
    select: ".price"
    value_template: "{{ value.split(' ')[0].replace(',', '.') | float }}"
    scan_interval: 3600
```   

```
    ## afvalbeheer Waardlanden    
  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    diftarcode: ""
    location: ######
    postcode: ######
    streetnumber: ######
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
    notrashtext: "geen"
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['groente_fruit_en_tuinafval', 'plastic_blik_en_drankkartons', 'papier', 'restafval'] %}
          {% set friendly_list = ['Groente Fruit en Tuinafval', 'Plastic Blik en Drankkartons', 'Papier', 'Restafval'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{friendly_list[loop.index0]}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %} 
```

```
# Sonoff RF Bridge / Ewelink application
sonoff:
  username: #############
  password: #############
  mode: local
  reload: always # update device list every time HA starts
```

```
energy:
zha_toolkit:
```

**Reply by matt8707** [reply]
post the whole file inside triple backticks, don't split it up or change anything

````
```
here
```
````

**Comment by dejongac** [comment]
```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


customize: !include customize.yaml
# packages: !include_dir_named packages/
automation: !include automations.yaml
frontend: !include themes.yaml
template: !include sidebar.yaml
 
lovelace:
  resources: !include lovelace/resources/resources.yaml

  dashboards:
    sidebar-dashboard:
      mode: yaml
      filename: lovelace/ui-lovelace.yaml
      title: Sidebar
      icon: mdi:tablet
      show_in_sidebar: true
 
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://rawgit.com/james-fry/home-assistant-mdi/master/home-assistant-mdi.html
 
# Text to speech
tts:
- platform: google_translate
 

sensor:
 
  # Formula 1
  - platform: formulaone_api
 
  # Date & Time
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
 
  - platform: template
    sensors:
      week_day:
        value_template: "{{ now().strftime('%A')}}"
      current_date:
        value_template: "{{ now().strftime('%d')}} {{ now().strftime('%B')}} {{ now().strftime('%Y')}}"
 
  # Brandstofprijzen
  # Euro95
  - platform: scrape
    name: Euro95 Advies
    resource: "https://www.unitedconsumers.com/brandstofprijzen"
    select: ".table div:nth-of-type(2) div:nth-of-type(3)"
    value_template: "{{ value |replace('€', '') |replace(',', '.') |round(3) }}"
    scan_interval: 3600 # be nice; once per hour only

  - platform: scrape
    name: Euro95 Tinq Concordiaweg
    resource: "https://www.tinq.nl/tankstations/gorinchem-concordiaweg#default"
    select: ".field--name-field-station-prices .taxonomy-term-Euro95 .field--name-field-prices-price-pump"
    value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
    scan_interval: 3600 # be nice; once per hour only
    
  - platform: scrape
    resource: "https://tankservice.app-it-up.com/Tankservice/v2/places/3337.png?lang=nl"
    name: Euro95 Argos.stationseweg
    select: ".price"
    value_template: "{{ value.split(' ')[0].replace(',', '.') | float }}"
    scan_interval: 3600
  
  # Diesel
  - platform: scrape
    name: Diesel Advies
    resource: "https://www.unitedconsumers.com/brandstofprijzen"
    select: ".table div:nth-of-type(2) div:nth-of-type(3)"
    value_template: "{{ value |replace('€', '') |replace(',', '.') |round(3) }}"
    scan_interval: 3600 # be nice; once per hour only

  - platform: scrape
    name: Diesel Tinq Concordiaweg
    resource: "https://www.tinq.nl/tankstations/gorinchem-concordiaweg#default"
    select: ".field--name-field-station-prices .taxonomy-term-Diesel .field--name-field-prices-price-pump"
    value_template: "{{ value | replace('€', '') | replace('EUR/L', '') | float | round(3) }}"
    scan_interval: 3600 # be nice; once per hour only
    
  - platform: scrape
    resource: "https://tankservice.app-it-up.com/Tankservice/v2/places/3337.png?lang=nl"
    name: Diesel Argos stationsweg
    select: ".price"
    value_template: "{{ value.split(' ')[0].replace(',', '.') | float }}"
    scan_interval: 3600

    ## afvalbeheer Waardlanden    
  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    diftarcode: ""
    location: #####
    postcode: ####
    streetnumber: ####
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
    notrashtext: "geen"
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['groente_fruit_en_tuinafval', 'plastic_blik_en_drankkartons', 'papier', 'restafval'] %}
          {% set friendly_list = ['Groente Fruit en Tuinafval', 'Plastic Blik en Drankkartons', 'Papier', 'Restafval'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{friendly_list[loop.index0]}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %} 


# Sonoff RF Bridge / Ewelink application
sonoff:
  username: #############
  password: #############
  mode: local
  reload: always # update device list every time HA starts

energy:
zha_toolkit:
```
