### DISCUSSION TITLE
light button with mushroom

### DISCUSSION THREAD

**Discussion by tunguskar** [matt8707/hass-config#122] [Q&A] [answered]
Hi there, 

At the moment I struggle with the mushroom light button you showed in the preview:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/2837624/200671903-308c0f94-b6ba-49e9-aa9b-68fb71bd1bf3.png">

I added my own popup to the first button:

```yaml
          - type: custom:button-card
            entity: light.lichter_eg
            name: Lichter
            template:
              - light
              - icon_shade
            double_tap_action:
              !include popup/licht_eg.yaml
```
the licht_eg.yaml

looks like this:

```yaml
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Licht EG
    card_mod:
      style:
        #popup header
        .:
    content:
      type: vertical-stack
      cards:
        - type: entities
          state_color: true
          show_header_toggle: false
          card_mod:
            class: content
          entities:

            - entity: light.licht_wohnzimmer_links
              secondary_info: last-changed
            - entity: light.licht_wohnzimmer_mitte
              secondary_info: last-changed
            - entity: light.licht_wohnzimmer_rechts
              secondary_info: last-changed
```

But it looks like this:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/2837624/200672595-50f7371e-11d5-4c12-954b-d48388c0ce04.png">

what mistake do I make and how is it possible to get the mushroom design you showed?

Btw. is it possible to hide the dimmer symbol when the lamp is not dimable?
