### DISCUSSION TITLE
Loader in mushroom cards

### DISCUSSION THREAD

**Discussion by Xitro01** [matt8707/hass-config#149] [Q&A]
I have a pop-up with a mushroom card with a couple of entities, like so:

```
- type: custom:mushroom-entity-card
  entity: switch.game_pc
  tap_action:
    action: toggle
```

The problem is that those entities are PC’s, so when clicked they don’t turn on immediately.
Is it possible to, when clicked, show a loader until it’s on (or off)?

I know that this dashboard already does something similar with /local/loader.svg, so maybe someone could help me out here.
