### DISCUSSION TITLE
Button-card template 'sidebar' is missing!

### DISCUSSION THREAD

**Discussion by Piero87** [matt8707/hass-config#152] [Q&A] [answered]
I have this error: Button-card template 'sidebar' is missing! but I can't understand what i'm missing:

this is my configuration.yaml

```
frontend: !include themes.yaml
template: !include sidebar.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /local/fonts.css?v=2.1
      type: css
```

then I added the sidebar.yaml file, themes.yaml and ui-lovelace.yaml

but this is the error:

<img width="284" alt="Screenshot 2023-01-15 alle 00 17 53" src="https://user-images.githubusercontent.com/768952/212501224-04ccdee4-84df-41d9-967b-eb41e5cf0606.png">

what could i have done wrong?

**Comment by Piero87** [comment, marked as answer]
I was missing a file, solved

**Reply by texasmouse** [reply]
Which file??

**Comment by Piero87** [comment]
I have anyway a question regarding this code in ui-lovelace.yaml:
```

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar
```

where is defined this entity:
`entity: sensor.template_sidebar` ? I don't understand the `template_` part
