### DISCUSSION TITLE
how to change the layout in a popup window with mushroom

### DISCUSSION THREAD

**Discussion by tunguskar** [matt8707/hass-config#171] [Q&A]
Hi,

I added some buttons on a popup window which looks like this:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/2837624/228530994-4c8ece8e-1fd9-4aad-8e7f-298c4bc16b42.png">

Code is this:

```yaml
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    #title: Terrasse
    #size: fullscreen
    card_mod:
      style: |
        .:
    content:
      type: vertical-stack
      cards:
        - type: custom:mushroom-title-card
          title: Terrasse
          subtitle: |-
            {% set total = 0 %}
            {% if is_state('light.licht_terrasse_seitlich', 'on') %}
              {% set total = total + 1 %}
            {% endif %}
            {% if is_state('light.licht_terrasse_tisch', 'on') %}
              {% set total = total + 1 %}
            {% endif %}
            Zur Zeit sind ({{total}}) Lichte/r an
          alignment: justify
        - type: horizontal-stack
          cards:
            - type: custom:mushroom-light-card
              entity: light.licht_terrasse_seitlich
              layout: vertical
...
```

Does anybody know how to get a little bit more contrast, or how to get a background to the single buttons. It seems that all settings I do where overwritten. like on the main window

<img width="282" alt="image" src="https://user-images.githubusercontent.com/2837624/228532178-6e8ce123-0840-46cf-98f3-0cffcb0476e8.png">
