### DISCUSSION TITLE
2 Template Sections in configuration.yaml - How to solve?

### DISCUSSION THREAD

**Discussion by Suschibomber** [matt8707/hass-config#212] [Q&A]
Hello, when I insert template: !include sidebar.yaml into configuration.yaml, home assistant complains that I have two template sections. **duplicated mapping key**

How do I get this error to disappear, or how do I format it correctly?

```
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes

template: !include sidebar.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module

template:
  - binary_sensor:
    # Stellt fest, ob die Waschmaschine läuft oder nicht
      - name: "Waschmaschine"
        unique_id: "Waschmaschine"
        state: ""
        device_class: running
        icon: mdi:washing-machine 

utility_meter:
  regen_woche:
    source: sensor.regen_heute 
    cycle: weekly
    unique_id: regen_woche
  regen_monat:
    source: sensor.regen_heute 
    cycle: monthly
    unique_id: regen_monat
  regen_jahr:
    source: sensor.regen_heute 
    cycle: yearly
    unique_id: regen_jahr
```

**Comment by Suschibomber** [comment]
Nobody could tell me the answer :( ?

**Reply by anarion80** [reply]
Well, you do have two template keys...

Best would be something like this I guess:

```
homeassistant:
  packages: !include_dir_named packages
  customize_domain:
    automation:
      initial_state: true
  allowlist_external_dirs:
    - /config
    - /config/www

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes
template: !include sidebar.yaml
```

so put your binary sensor template in a dedicated file in a directory called `packages` for example

**Comment by Suschibomber** [comment]
So I copy your complete code into my configuration.yaml and create a folder called "packages". 
In this folder "packages" I create a new file for example template_binary_sensors.yaml and then cut and paste this part into my configuartion.yaml. 
Then my file "template_binary_sensors.yaml" looks something like this:

```
 - binary_sensor:
    # Stellt fest, ob die Waschmaschine läuft oder nicht
      - name: "Waschmaschine"
        unique_id: "Waschmaschine"
        state: ""
        device_class: running
        icon: mdi:washing-machine  
    # Stellt fest, ob der Trockner läuft oder nicht
      - name: "Trockner"
        unique_id: "Trockner"
        state: ""
        device_class: running
        icon: mdi:tumble-dryer        
    # Stellt fest, ob die Spuelmaschine läuft oder nicht
      - name: "Spuelmaschine"
        unique_id: "Spuelmaschine"
        state: ""
        device_class: running
        icon: mdi:dishwasher        
    # Stellt fest, ob der Xiaomi G10 geladen wird oder nicht
      - name: "XiaomiG10"
        unique_id: "XiaomiG10"
        state: ""
        device_class: battery_charging
        icon: mdi:vacuum                
    # Stellt fest, ob das Galaxy S21 Ultra grade geladen wird oder nicht
      - name: "Galaxy S21 Ultra Charging"
        unique_id: "galaxys21ultraLeoCharging"
        state: "{{not is_state('sensor.galaxy_s21_ultra_battery_state','discharging') }}"
    # Dieses Sensor ist an, wenn jemand zu Hause ist
      - name: Ist jemand zuhause
        unique_id: "isAnyoneAtHome"
        state: >
          {{ is_state('device_tracker.galaxy_s21_ultra_5g', 'home')
             or is_state('device_tracker.pixel_6a', 'home') }}
  - sensor:
    # Stellt fest, wie oft die Katzenklos benutzt wurden
      - name: "Katzenklos Zaehler Gesamt"
        unique_id: "Katzenklos"
        state: >-
            {{ (float(states('counter.katzenklo_links'))) + (float(states('counter.katzenklo_rechts'))) |round|int }}
        icon: mdi:toilet

  - sensor:
    - name: "Regen Heute"
      unit_of_measurement: mm
      state_class: total_increasing
      unique_id: regen_heute
      state: >-
        {% set count = states('counter.regensensor_flips') | int(0) %}
        {% set mm = count * 0.1 %}
        {% if count >= 0 %}
          {{ mm|round(1, 'floor') }}
        {% endif %}
      availability: "{{ (states('counter.regensensor_flips') not in ('unknown', 'unavailable')) }}"
    - name: "Regen Intensitaet"
      unique_id: regen_intensitaet
      state: >
          {% set lastTip = (as_timestamp(now()) - as_timestamp(states.binary_sensor.diy_zigbee_regenmesser_contact.last_changed)) %}
          {% set betweenTips = states('sensor.regen_sensor_zeit_zwischen_tropfen') | as_timedelta %}
          {% set max_time = max(lastTip, betweenTips.total_seconds()) %}
                       
          {{ (0,30303 / (max_time / 3600)) | round(1, default=0) }}
      state_class: measurement
      device_class: precipitation_intensity
      unit_of_measurement: "mm/h"
  - trigger:
      - platform: state
        entity_id: binary_sensor.diy_zigbee_regenmesser_contact
    sensor:
      - name: Regensensor Zeit zwischen Tropfen
        unique_id: regen_sensor_zeit_zwischen_tropfen
        state: >
            {{ (now() - trigger.from_state.last_changed).total_seconds() }}
        state_class: measurement
        unit_of_measurement: "s"
```

At the top of the new file there doesn't have to be "template:" because that happens automatically?

```
homeassistant:
  packages: !include_dir_named packages
  customize_domain:
    automation:
      initial_state: true
  allowlist_external_dirs:
    - /config
    - /config/www
```
I just don't quite understand this part yet. Couldn't you have just included the sidebar.yaml somehow?
