### DISCUSSION TITLE
Combine existing template integration

### DISCUSSION THREAD

**Discussion by hancooo** [matt8707/hass-config#95] [General]
My mind is a bit stumped on this one. 
I am already using the template integration to run a calculation on energy reading. 
How would I add the `template: !include sidebar.yaml` in? 

![image](https://user-images.githubusercontent.com/20757683/194669286-5ccf9b8d-db45-4a0f-af20-84ad388e3bd6.png)

```
template:
  - sensor:
    - name: Daily Usage Cost
      unit_of_measurement: £
      device_class: energy
      state_class: measurement
      state: >
        {{ states('sensor.daily_use_kwh') | float(default=0.0) | multiply(0.35314) | float +  0.4267}}

template: !include sidebar.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend: !include themes.yaml
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
```
