### ISSUE TITLE
[Question] Button card in second row full width?

### ISSUE THREAD

**Issue by Edwin-Luijten** [matt8707/hass-config#112]
Is it possible to have a square with at the bottom a single button-card taking up the whole row?
![New Project](https://user-images.githubusercontent.com/1339637/197584830-d0e2c71a-26e0-4a08-9366-34d14ef16140.png)

**Comment by matt8707** [comment]
Yes, if you use layout-card instead of grid. 

So instead of `custom:grid-layout → grid`
use `custom:grid-layout → custom:grid-layout`

**Comment by Edwin-Luijten** [comment]
Thanks for the prompt reply, I'm trying the below config which does not seem to give the desired result (the whole square is not visible at all).

```yaml
  #################################################
  #                                              
  #     HOME                   
  #                                               
  #################################################

  - type: custom:grid-layout
    title: Home
    view_layout:
      grid-area: home
    columns: 2
    cards:
      - type: custom:button-card
        entity: person.{id}
        name: Edwin
        tap_action: !include ../popup/{id}.yaml
        hold_action:
          action: none
        template: person

      - type: custom:button-card
        entity: person.ilona
        name: Ilona
        tap_action: !include ../popup/{id}.yaml
        hold_action:
          action: none
        template: person

      - type: custom:grid-layout
        columns: 1
        cards:
          - type: custom:button-card
            template: custom_washer_state_grid
            variables:
              ulm_custom_washer_grid_machine_state: switch.washer
              ulm_custom_washer_grid_job_state: sensor.washer_washer_job_state
              ulm_custom_washer_grid_completion_timestamp: sensor.washer_remaining_time
```

**Comment by matt8707** [comment]
not same config as `type: grid`
https://github.com/thomasloven/lovelace-layout-card#grid-layout

**Comment by Edwin-Luijten** [comment]
Ah indeed, I think I still fail to grasp the idea of configuring it, I started with just trying to get the 2 person cards in there, but the root element stays empty.
```yaml
  #################################################
  #                                               #
  #                  CAR                          #
  #                                               #
  #################################################

  - type: grid
    title: CAR
    view_layout:
      grid-area: car
    columns: 1
    cards:
      - type: custom:button-card
        entity: binary_sensor.q_charging
        name: EV6
        tap_action:
          action: navigate
          navigation_path: /lovelace/car?kiosk
        template:
          - car

  #################################################
  #                                               #
  #                  HOME                         #
  #                                               #
  #################################################
  - type: custom:grid-layout
    title: Home
    view_layout:
      grid-area: home
    layout:
      grid-template-columns: 50%
      grid-template-rows: auto
      grid-template-areas: |
        "a"
        "b"
    cards:
      - type: custom:button-card
        view_layout:
          grid-area: a
        entity: person.{id}
        name: Edwin
        tap_action: !include ../popup/{id}.yaml
        hold_action:
          action: none
        template: person

      - type: custom:button-card
        entity: person.{id}
        view_layout:
          grid-area: b
        name: Ilona
        tap_action: !include ../popup/{id}.yaml
        hold_action:
          action: none
        template: person
```
![image](https://user-images.githubusercontent.com/1339637/198036683-b3f7bce9-b6f3-4061-b4c0-0337631bd0d2.png)
