### ISSUE TITLE
Migrate to 1920x1200 tablet

### ISSUE THREAD

**Issue by CarpeDiemRo** [matt8707/hass-config#12]
Hi, @matt8707  you did a wonderful job. Inspired by your code I implemented my own view on an AsusZenpad with 1200x800 resolution. Today I switched on a Huawei T5 with a better screen and a better resolution. Unfortunately, the images are too big and I have to change their sizes. Which is normal. I want to ask you which is the simplest way to change the  size of the:
1. button card sizes in order to fit in the screen
2. popup window in order to fit in screen and text size. I was wondering if it is a method to shrink the area?!
 Here are a few examples

- 
![Screenshot_20200611-200222](https://user-images.githubusercontent.com/38489167/84418049-3fa59000-ac1f-11ea-8564-8a54509da01d.jpg)
 The cards are too big and go outside of the visible area. 
I tried to reduce the size from here but the text remains too big and the aspect was not ok
```
                style:
                  background: none
                  box-shadow: none
                  width: calc(400px + 485px + 300px)
                card:
                  type: custom:layout-card
                  column_num: 3
                  column_width: [400, 485, 300]
                  layout: vertical
```

- 
![Screenshot_20200611-200328](https://user-images.githubusercontent.com/38489167/84418311-acb92580-ac1f-11ea-9df4-45f62bcacc2d.jpg)
The card is too big and I want to reduce it but I could not identify the code part that controls his size

- 
![Screenshot_20200611-200143](https://user-images.githubusercontent.com/38489167/84418399-d2462f00-ac1f-11ea-9bf1-1fa8cecbcb14.jpg)
The card is too long/big and it should be resized. I could not identify the code that controls the card size
