### ISSUE TITLE
Not understanding how youtube_watching.yaml actually works

### ISSUE THREAD

**Issue by johntdyer** [matt8707/hass-config#125]
So AFAIK there is no rest: integration, there are rest platforms in various integrations, ie switches, sensor, ect ... so I am curious how youtube_watching.yaml actually works given its included with all the other various packages .... Shouldnt it be more like the following ? 

```yaml
sensor:
  - platform: rest
    authentication: basic
    username: !secret github_username
    password: !secret github_access_token
    resource: https://api.github.com/repos/esphome/esphome/releases/latest
```
