### ISSUE TITLE
Circle Slider cannot work with "type: custom:swipe-card", Please assist. 

### ISSUE THREAD

**Issue by horacecar** [matt8707/hass-config#136]
my light have a little more need to use the swipe-card for next pages. I tested the Circle Slider cannot work with "type: custom:swipe-card", when I tap the circle and slide up and down nothing happens.

```
      - type: grid
        title: Living Room
        square: false
        view_layout:
          grid-area: lvrm
        columns: 1
        cards:
          - type: custom:swipe-card
            start_card: 1
            reset_after: 10
            parameters:
              roundLengths: true
              effect: coverflow
              speed: 650
              spaceBetween: 20
              threshold: 7
              coverflowEffect:
                rotate: 80
                depth: 300
            cards:
              - type: grid
                columns: 3
                cards:
                  - type: custom:button-card
                    entity: binary_sensor.living_room_motion_sensor_1
                    template:
                      - sensor
                      - icon_sensor
                    variables:
                      icon_template: icon_sensor
                      entity_battery_level: sensor.living_room_motion_sensor_1_battery_level
                  - type: custom:button-card
                    entity: light.living_room_tv_light_1
                    template:
                      - light
                      - icon_led_strip_light
                    variables:
                      icon_template: icon_led_strip_light
                  - type: custom:button-card
                    entity: light.living_room_sofa_light_1
                    template:
                      - light
                      - icon_shade
                    variables:
                      icon_template: icon_shade
                  - type: custom:button-card
                    entity: light.living_room_corridor_ceiling_light_1
                    template:
                      - light
                      - icon_ceiling_light_1
                    variables:
                      icon_template: icon_ceiling_light_1
                  - type: custom:button-card
                    entity: light.living_room_ceiling_led_strip_light_1
                    template:
                      - light
                      - icon_led_strip_light
                    variables:
                      icon_template: icon_led_strip_light
                  - type: custom:button-card
                    entity: light.dining_room_ceiling_light_1
                    template:
                      - light
                      - icon_dining_room_ceiling_light
                    variables:
                      icon_template: icon_dining_room_ceiling_light
              - type: grid
                columns: 3
                cards:
                  - type: custom:button-card
                    entity: light.gateway_light_7c49eb1b1ac6
                    template:
                      - rgb_light
                      - icon_hue
                    variables:
                      icon_template: icon_hue
                  - type: custom:button-card
                    entity: light.pet_light_1
                    template:
                      - light
                      - icon_desk_light
                    variables:
                      icon_template: icon_desk_light
                  - type: custom:button-card
                    entity: switch.pet_feeder_1
                    template:
                      - switch
                      - icon_pet_feeder
                      - loader
                      - lock
                    variables:
                      icon_template: icon_pet_feeder
                  - type: custom:button-card
                    entity: light.living_room_spotlight_1
                    template:
                      - light
                      - icon_spot
                    variables:
                      icon_template: icon_spot
                  - type: custom:button-card
                    entity: light.living_room_spotlight_2
                    template:
                      - light
                      - icon_spot
                    variables:
                      icon_template: icon_spot
                  - type: custom:button-card
                    entity: media_player.samsung_tv_2
                    template:
                      - light
                      - icon_tv
                      - loader
                    variables:
                      icon_template: icon_tv
              - type: grid
                columns: 3
                cards:
                  - type: custom:button-card
                    entity: climate.dining_room_ac_1
                    template:
                      - base
                      - climate
                      - icon_climate_1
                    variables:
                      entity_1: sensor.dining_room_temperature
                      entity_2: sensor.dining_room_humidity
                      circle_input: >
                        [[[
                          if (entity) {
                              return entity.state === 'cool'
                                  ? Math.round(entity.attributes.temperature).toString()
                                  : Math.round(entity.attributes.current_temperature).toString();
                          }
                        ]]]
                      circle_input_unit: '°C'

```
