### ISSUE TITLE
Popup error

### ISSUE THREAD

**Issue by FillHK** [matt8707/hass-config#138]
Thank you for so a nice job done.

The issue is with popup:
```
      - type: grid
        title: Hemma
        view_layout:
          grid-area: hemma
        columns: 2
        cards:

          - type: custom:button-card
            entity: person.matte
            name: Mattias
            triggers_update:
              - sensor.matte_last_changed
            double_tap_action:
              !include popup/hemma_mattias.yaml
            variables:
              retain: sensor.matte_last_changed
            template:
              - person
              - circle
```
Error: unknown tag !<!include>
