### ISSUE TITLE
When Sidebar hides and displays button Toggle, the button card will not respond to resize

### ISSUE THREAD

**Issue by aj-chan** [matt8707/hass-config#140]
in the video the only the media and living room area is working with the response of button card resize when Sidebar hides and displays button Toggle.

<img width="363" alt="button1" src="https://user-images.githubusercontent.com/55744541/204753324-67801bc4-a1e2-422c-9c47-348ac13792a0.png">

I found out if I want a swipe card on the panel to have a button area 3x2 .  I need to set " type: custom:swipe-card "  to " - type: grid    columns: 3" also I need to enable "square: false". Otherwise, there will be a big gap between the footer or other area. ref: 'https://www.home-assistant.io/dashboards/grid/'

But once I enable "square: false", the button will not response to resize when I toggle Home Assistant's sidebar hides and displays button. the card will overflow and broken

![p2](https://user-images.githubusercontent.com/55744541/204753712-f07a8bcd-74fc-48e8-94df-9a5f0076072d.png)

![p1](https://user-images.githubusercontent.com/55744541/204753682-36bd257e-0a7d-4041-aa1b-5ba500040aee.png)

https://user-images.githubusercontent.com/55744541/204752475-09794967-1ea2-4d8c-b80d-fd052f9ee49b.mp4

```
      #               Living  Room               #


      - type: grid
        title: Living Room
        view_layout:
          grid-area: lvrm
        columns: 1
        cards:
          - type: custom:swipe-card
            start_card: 1
            reset_after: 10
            parameters:
              effect: coverflow
              speed: 450
              spaceBetween: 20
              threshold: 5
              coverflowEffect:
                rotate: 80
                depth: 100
            cards:
              - type: grid
                columns: 3
                cards:
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
              - type: grid
                columns: 3
                cards:
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light

      #                     Kitchen                  #


      - type: grid
        title: Kitchen
        square: false
        view_layout:
          grid-area: kitchen
        columns: 1
        cards:
          - type: custom:swipe-card
            start_card: 1
            reset_after: 10
            parameters:
              effect: coverflow
              speed: 450
              spaceBetween: 20
              threshold: 5
              coverflowEffect:
                rotate: 80
                depth: 100
            cards:
              - type: grid
                columns: 3
                cards:
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
              - type: grid
                columns: 3
                cards:
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
                  - type: custom:button-card
                    entity: light.ceiling_lights
                    template:
                      - light
                      - icon_worktop_light
                    variables:
                      icon_template: icon_worktop_light
```
