### ISSUE TITLE
mini-graph-card temperature humidity

### ISSUE THREAD

**Issue by luckhy2882** [matt8707/hass-config#164]
![擷取](https://user-images.githubusercontent.com/125120787/220648513-b1eda1c0-d299-435b-ba76-a143bf70aa1c.PNG)
I'm a novice and don't know how to change "BASE"

**Comment by ivancristina** [comment]
Hi @luckhy2882, may you be able to post the template you made? It looks very interesting

**Comment by callumgare** [comment]
I’d also love to see it!

**Comment by luckhy2882** [comment]
> Hi @luckhy2882, may you be able to post the template you made? It looks very interesting

see you

**Comment by luckhy2882** [comment]
> 我也很想看！

- type: custom:button-card
                    entity: sensor.m1_humidity
                    name: 室内湿度
                    tap_action: more-info #!include popup/temperature.yaml
                    hold_action:
                      action: none
                    custom_fields:
                      graph:
                        card:
                          entities:
                            - sensor.m1_humidity
                    template:
                      - humidity
                      - icon_humidity
                    variables:
                      popup_name: 湿度监测

temperature:
    template:
      - base
    show_state: false
    custom_fields:
      circle: >
        [[[ {
        const temperature = Math.round(entity.state);
        return `<svg viewBox="0 0 50 50"><circle cx="25" cy="25" r="20.5" stroke="#313638" stroke-width="1.5" fill="#FFFFFF08" style="
        transform: rotate(-90deg); transform-origin: 50% 50%;" />
        <text x="50%" y="54%" fill="#8d8e90" font-size="14" text-anchor="middle" alignment-baseline="middle" dominant-baseline="middle" dominant-baseline="middle">${temperature}°C</text></svg>`; } ]]]
      graph:
        card:
          type: "custom:mini-graph-card"
          line_color: "#3182b7"
          line_width: 4
          font_size: 75
          hours_to_show: 12
          show:
            name: false
            icon: false
            state: false
            legend: false
            labels: false
          color_thresholds:
            - value: 20
              color: "#26c941"
            - value: 25
              color: "#64c91c"
            - value: 28
              color: "#d4c11c"
            - value: 30
              color: "#d1861d"
            - value: 32
              color: "#de4314"
            - value: 35
              color: "#fa0505"
            - value: 40
              color: "#c92626"
    styles:
      name: [top: 57%, left: -12%, width: 100%, position: absolute]
      custom_fields:
        graph: [bottom: 0%, left: 0%, width: 100%, position: absolute]
        circle:
          - display: initial
          - width: 90%
          - letter-spacing: 0.03vw
          - margin: -6% -6% 0 0
          - justify-self: end
          - opacity: 1
        icon:
          - width: 67%
          - fill: "#9da0a2"

**Comment by callumgare** [comment]
Thanks for that!

**Comment by ClementRoyer** [comment]
Hi @NicooooGit ,

I found the solution, simply add ` before to the returned string, it's supposed to be a string template..

```
  template:
    - base
  aspect_ratio: 1/1
  show_state: true
  custom_fields:
    circle: >
      [[[ {
        const temperature = Math.round(entity.state);
        return `<svg viewBox="0 0 50 50"><circle cx="25" cy="25" r="20.5" stroke="#313638" stroke-width="1.5" fill="#FFFFFF08" style="transform: rotate(-90deg); transform-origin: 50% 50%;" />
            <text x="50%" y="54%" fill="#8d8e90" font-size="14" text-anchor="middle" alignment-baseline="middle" dominant-baseline="middle" dominant-baseline="middle">${temperature}°C</text></svg>`;
      } ]]]

    graph:
      card:
        type: "custom:mini-graph-card"
        height: 800
        upper_bound: 33
        lower_bound: 14
        line_width: 12
        align_state: left
        group: false
        points_per_hour: 2
        hour24: true
        hours_to_show: 12
        tap_action: none
        show:
          name: false
          icon: false
          state: false
          legend: false
          labels: false
          points: false
        color_thresholds:
          - value: 10
            color: "#A9FFFF"
          - value: 17
            color: "#2a9d8f"
          - value: 18.5
            color: "#e9c46a"
          - value: 19.5
            color: "#f4a261"
          - value: 20
            color: "#e76f51"
        circle:
          display: initial
          width: 90%
          letter-spacing: 0.03vw
          margin: -6% -6% 0 0
          justify-self: end
          opacity: 1
  styles:
    custom_fields:
      graph: [bottom: -25%, left: -25%, width: 150%, position: absolute]
      button:
        [bottom: 0%, left: -25%, width: 150%, position: absolute, opacity: 0]
      icon:
        - width: 60%
        - fill: "#9da0a2"
```
