### ISSUE TITLE
Configs overwrite existing default dashboard

### ISSUE THREAD

**Issue by boojew** [matt8707/hass-config#167]
So, maybe I am missing something obvious, but by using ui-lovelace in the root config directory we lose our existing dashboard. I am not sure how to avoid this

**Comment by anarion80** [comment]
@boojew I work around this by naming my instance of matt8707's dashboard `ui-lovelace-tablet` and then in the config:

```
lovelace:
  dashboards:
    lovelace-tablet:
      mode: yaml
      title: Tablet
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: ui-lovelace-tablet.yaml
```

This way I have both this, and the 'old' dashboards.
