### ISSUE TITLE
Problem with remote.send_command

### ISSUE THREAD

**Issue by roh735** [matt8707/hass-config#18]
Hello, sorry for stupid questions again but i have this problems and don't really know what the problem.
remote i have its RM pro and i connect it to secrets like this
or should i install "broadlink manager" to PC and set it up there?
```
broadlink_host: 111.111.111.111
broadlink_mac: '11:1a:11:1a:1a:1a'
```

also for example i have switch.yaml code:

```
      tv_lg:
        friendly_name: Tv
        icon_template: custom:tv
        value_template: "{{ is_state('media_player.lg_webos_tv_e03c', 'on') }}"
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.lg_webos_tv_e03c
          - service: remote.send_command
            data:
              entity_id: remote.lg_webos_tv_e03c
              command: menu
        turn_off:
          - service: input_boolean.turn_on
            entity_id: input_boolean.lg_webos_tv_e03c
          - service: media_player.turn_off
            entity_id: media_player.lg_webos_tv_e03c
```
when i trying to press turn on TV from this switch its giving error, photo attached 'failed to call service' and I check, I dont have this service in 'Services menu'

![image](https://user-images.githubusercontent.com/66237408/95277005-52695380-0812-11eb-8192-4d43fbf19893.png)

**Comment by matt8707** [comment]
add broadlink as integration using ui
https://www.home-assistant.io/integrations/broadlink

image where you should stop in the mobile app, dont add or you'll lose local control
https://user-images.githubusercontent.com/36163594/93138133-d2ead780-f6de-11ea-9970-a66060d066a9.jpeg

Now remote.send_command should work, 
you have to learn ir codes and test it out in dev tools

this part seems wrong
```
          - service: remote.send_command
            data:
              entity_id: remote.lg_webos_tv_e03c
              command: menu
```

remote send command -> integration remote.broadlink (or whatever you name it) -> command is secret ir code
```
          - service: remote.send_command
            data:
              entity_id: remote.broadlink
              command: !secret ir_fan_speed
```
