### ISSUE TITLE
Problem with  fullykiosk_screen \ fullykiosk_screensaver \ fullykiosk_brightness_slider

### ISSUE THREAD

**Issue by roh735** [matt8707/hass-config#19]
so this 3 setups don't work, I don't know what can be a problem, battery and all other things works as it should and all connected correctly, may be its should be some set up in Fullykiosk app? I bought app if its a problem can you please let me know what need to turn on/off in app? or its something else don't let me set it up correctly?

![image](https://user-images.githubusercontent.com/66237408/95277509-8bee8e80-0813-11eb-82c2-c33da5b20c30.png)

![image](https://user-images.githubusercontent.com/66237408/95277532-a1fc4f00-0813-11eb-98ab-c436e845e322.png)
![image](https://user-images.githubusercontent.com/66237408/95277559-b0e30180-0813-11eb-9bd5-90a765850942.png)
![image](https://user-images.githubusercontent.com/66237408/95277574-bc362d00-0813-11eb-9412-4d602aa3b8be.png)

**Comment by matt8707** [comment]
Fullykiosk changed some names in the api. 
`currentFragment` `screensaver` is now `isInScreensaver` `true` etc..
I'll update the changes tomorrow

**Comment by roh735** [comment]
ok, thank you, waiting on your update.
Thank you, closing this issue in this case.

**Comment by Mohdbakr** [comment]
also, isScreenOn changed to screenOn

**Comment by matt8707** [comment]
Thanks, I missed that

**Comment by roh735** [comment]
sorry but for me its didnt help, same problem

see my code please help
switch.yaml
```
switch:

  - platform: command_line
    switches:
      fullykiosk_screen:
        friendly_name: Display
        command_on: !secret fullykiosk_screen_on
        command_off: !secret fullykiosk_screen_off
        command_state: !secret fullykiosk_screen_state
        value_template: "{{ value == 'on' }}"

  - platform: template
    switches:
      fullykiosk_screensaver:
        friendly_name: Screensaver
        icon_template: mdi:power-sleep
        value_template: "{{ is_state_attr('sensor.fullykiosk', 'isInScreensaver', true) }}"
        turn_on:
          - service: shell_command.fullykiosk_screensaver_on
        turn_off:
          - service: shell_command.fullykiosk_screensaver_off
```
input.yaml

```
input_number:

  fullykiosk_brightness_slider:
    name: Brightness
    icon: mdi:brightness-6
    initial: 20
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
```

sidebar_information.yaml
```
- type: entities
                      title: Tablet
                      class: add_header
                      show_header_toggle: false
                      entities:

                        - entity: switch.fullykiosk_screen

                        - type: custom:slider-entity-row
                          entity: input_number.fullykiosk_brightness_slider
                          hide_state: false

                        - entity: switch.fullykiosk_screensaver

                        - entity: sensor.fullykiosk_battery

                        - entity: sensor.fullykiosk_plugged

                        - entity: binary_sensor.fullykiosk_motion

                        - type: custom:bar-card
                          width: 55%
                          height: 2em
                          decimal: 0
                          unit_of_measurement: '%'
                          positions: *bar_card_positions
                          severity: *bar_card_severity
                          entity_row: true
                          entities:

                            - entity: sensor.fullykiosk_memory
                              name: Memory - 2GB
                              icon: mdi:memory
                              tap_action:
                                action: call-service
                                service: homeassistant.update_entity
                                service_data:
                                  entity_id: sensor.fullykiosk_memory

                            - entity: sensor.fullykiosk_storage
                              name: Storage - 32GB
                              icon: mdi:sd
                              tap_action:
                                action: call-service
                                service: homeassistant.update_entity
                                service_data:
                                  entity_id: sensor.fullykiosk_storage
```

**Comment by matt8707** [comment]
```yaml
  - platform: rest
    name: fullykiosk
    json_attributes:
      ['batteryLevel', 'screenBrightness', 'plugged', 'motionDetectorStatus', 
      'lastAppStart', 'internalStorageFreeSpace', 'internalStorageTotalSpace', 
      'ramFreeMemory', 'ramTotalMemory', 'isInScreensaver']
    resource: !secret fullykiosk_rest_resource
    value_template: '{{ value_json.screenOn }}'
    scan_interval: 10
```
also double check secrets url/password
