### ISSUE TITLE
Vacuum More Info (whack-a-mole needed)

### ISSUE THREAD

**Issue by Xitro01** [matt8707/hass-config#205]
Hey guys,

Since an update, not sure which, the more info stuff appeared again.
![Knipsel](https://github.com/matt8707/hass-config/assets/19844787/6c376f21-795e-4469-b240-5ca5fa25f21a)

I guess some CSS whack-a-mole is needed.

I tried some stuff, but was unable to remove it myself.

It is related to these lines of code in footer_vacuum.yaml:
```yaml
- type: custom:more-info-card
  entity: vacuum.roborock_vacuum_s5
  card_mod:
    style:
      # hide everything but ha-select
      $: |
        h1 {
          display: none !important;
        }
      .: |
        h1, state-card-content {
          display: none !important;
        }
        .card-content {
          padding: 1.5em 0 0 0.7em;
        }
      more-info-vacuum$:
        .: |
          div.flex-horizontal>div, div:nth-child(2), ha-attributes {
            display: none;
          }
          ha-select {
            display: contents;
          }
        ha-select:
          $:
            # no icon so remove label inset
            .: |
              .mdc-floating-label {
                inset-inline-start: 0 !important;
              }
            # fix transparent menu background color
            mwc-menu$: |
              mwc-list {
                background: var(--card-background-color);
              }
```

Thanks in advance.

**Comment by OskarLebuda** [comment]
I've fixed this config in my project. I've also change the buttons to the selects for water volume and the suction level
This is my entire file `footer_vacuum.yml`. Change entity have fun ✌

![image](https://github.com/matt8707/hass-config/assets/10373127/b614a2be-cd0c-45b5-bc09-e741b6bf25d0)


```yaml
action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Vacuum
    timeout: 300000
    style: |
      --popup-max-width: calc(385px + 495px);
      --primary-color: transparent; /* hide timeout progress */
    card_mod:
      style:
        # card divider border
        layout-card$grid-layout$: |
          hui-vertical-stack-card {
            border-right: 1.5px solid rgba(0, 0, 0, 0.2);
            border-radius: 0;
            transition: none;
          }
          /* phone */
          @media screen and (max-width: 800px) {
            hui-vertical-stack-card {
              border-right: none;
              border-bottom: 1.5px solid rgba(0, 0, 0, 0.2);
            }
          }
    content:
      type: custom:layout-card
      layout_type: custom:grid-layout
      layout:
        margin: 0
        grid-template-columns: 385px 495px
        grid-template-rows: 1fr
        grid-template-areas: |
          "info map"
        mediaquery:
          #phone
          "(max-width: 800px)":
            grid-template-columns: 1fr
            grid-template-rows: repeat(2, 1fr)
            grid-template-areas: |
              "info"
              "map"
      cards:
        - type: vertical-stack
          view_layout:
            grid-area: info
          cards:
          - type: entities
            title: Overview
            card_mod:
              class: header
              style: |
                .card-content {
                  padding: var(--tablet-popup-content-padding);
                  padding-bottom: 0;
                }
            entities:

            - entity: vacuum.henryk

            - type: custom:bar-card
              width: 55%
              height: 2em
              decimal: 0
              unit_of_measurement: '%'
              positions:
                icon: outside
                indicator: 'off'
                name: outside
              severity:
                - color: '#303435'
                  from: 11
                  to: 999
                - color: '#6d2525'
                  from: 0
                  to: 10
              entity_row: true
              entities:
                - entity: vacuum.henryk
                  attribute: battery_level
                  name: Battery level
                  icon: mdi:battery
                - entity: sensor.henryk_filter_left
                - entity: sensor.henryk_main_brush_left
                - entity: sensor.henryk_side_brush_left
                - entity: sensor.henryk_sensor_dirty_left

            - entity: select.henryk_water_volume

            - entity: select.henryk_suction_level

          - type: custom:mod-card
            card_mod:
              style:
                # horizontal bottom buttons
                hui-horizontal-stack-card$: |
                  #root {
                    justify-content: space-evenly !important;
                    padding: var(--tablet-popup-button-padding);
                  }
            card:
              type: horizontal-stack
              cards:
                - type: custom:button-card
                  entity: vacuum.henryk
                  icon: mdi:play-pause
                  tap_action:
                    action: call-service
                    service: >
                      [[[
                        return `[[[
                          return entity.state === 'docked' || entity.state === 'paused'
                            ? 'vacuum.start'
                            : 'vacuum.pause';
                        ]]]`
                      ]]]
                    service_data:
                      entity_id: vacuum.henryk
                  template: icon_only

                - type: custom:button-card
                  entity: vacuum.henryk
                  icon: mdi:battery-charging
                  tap_action:
                    action: call-service
                    service: vacuum.return_to_base
                    service_data:
                      entity_id: vacuum.henryk
                  template: icon_only

                - type: custom:button-card
                  icon: mdi:delete-empty
                  tap_action:
                    action: call-service
                    service: vacuum.send_command
                    service_data:
                      entity_id: vacuum.henryk
                      command: app_goto_target
                      params: [16821,23105]
                  template: icon_only

        - type: custom:xiaomi-vacuum-map-card
          title: Map
          view_layout:
            grid-area: map
          card_mod:
            class: header
            style: |
              ha-card {
                --map-card-primary-color: #FFFFFF10;
                --map-card-secondary-color: none;
                --map-card-secondary-text-color: #9da0a2;
                --map-card-zoomer-background: none;
                --map-card-predefined-rectangle-fill-color: none;
                --map-card-predefined-rectangle-line-color: none;
                --map-card-predefined-rectangle-line-color-selected: rgba(255, 255, 255, 0.5);
                --map-card-predefined-rectangle-fill-color-selected: rgba(42, 124, 194, 0.1);
                --map-card-predefined-rectangle-icon-background-color-selected: rgb(42, 124, 194);
                --map-card-internal-big-radius: 0.6em !important;
              }
              div.controls-wrapper {
                display: none !important;
              }
              div.map-wrapper, div.controls-wrapper {
                padding: var(--tablet-popup-content-padding);
                padding-top: 0;
                padding-bottom: 0;
                letter-spacing: normal;
              }
              div.tiles-wrapper, div.vacuum-controls, #map-zoomer-overlay {
                display: none;
              }
              div.map-controls-wrapper {
                padding-top: 24px;
              }
              paper-button {
                --mdc-icon-size: 2em;
                color: #9da0a2 !important;
                padding: 0.42em;
              }
          language: en
          entity: vacuum.henryk
          map_source:
            camera: camera.henryk_map
          calibration_source:
            camera: true
          map_locked: true
          map_modes:
            - template: vacuum_clean_zone
            - template: vacuum_clean_zone_predefined
              predefined_selections:
                - zones: [[14895, 20640, 18409, 24058]]
                  icon:
                    name: mdi:silverware-fork-knife
                    x: 16708
                    y: 22291
                - zones: [[15208, 17278, 20204, 20980]]
                  icon:
                    name: mdi:bed
                    x: 17706
                    y: 19043
                - zones: [[18170, 20925, 23138, 25026]]
                  icon:
                    name: mdi:door
                    x: 22293
                    y: 21864
                - zones: [[21474, 24942, 27269, 28873]]
                  icon:
                    name: mdi:sofa
                    x: 24401
                    y: 26736
                - zones: [[17687, 24885, 21487, 28816]]
                  icon:
                    name: mdi:speaker
                    x: 19757
                    y: 26622
            - template: vacuum_goto
            - template: vacuum_follow_path

```
