### ISSUE TITLE
Help in creating the popup for the lights

### ISSUE THREAD

**Issue by Stinocon** [matt8707/hass-config#32]
Hello!
I'm trying to integrate the configuration part under Light and Sensors, to be exact I'm interested in the vertical dimmer and color selector.
I am not with lovelace in yaml mode.

I managed to generate this code that actually opens the popup with the slider but now I don't understand how to add the circles for the color selector. Can you please help me?

```
type: glance
entities:
  - entity: light.scrivania
    name: Scivania
    tap_action:
      action: toggle
    double_tap_action:
      action: fire-dom-event
      browser_mod:
        command: popup
        title: Test
        card:
          type: 'custom:light-popup-card'
          entity: light.scrivania
          icon: 'mdi:led-strip'
          borderRadius: 12px
```

Thanks
