### ISSUE TITLE
Hold action in Media section doesn't work

### ISSUE THREAD

**Issue by damiano75** [matt8707/hass-config#59]
Hi Matt,
do you know why only in Media section (swipe card) hold action doesn't work?
The same card in the other sections works fine.
My card is this one:

```
          - type: custom:button-card
            entity: media_player.sonos_one
            name: Sonos One
            hold_action:
                action: fire-dom-event
                browser_mod:
                 command: popup
                 title: Sonos One
                 card:
                    type: custom:custom-sonos-card
                    Optional settings:
                    name: '' 
                    groupsTitle: '' 
                    groupingTitle: '' 
                    favoritesTitle: '' 
                    headerImage: '' 
                    shuffleFavorites: false 
                    noMediaText: 'No media selected' 
                    allVolumesText: 'All volumes'
                    entityNameRegexToReplace: 'SONOS ' # Regex pattern to replace parts of the entity names
                    entityNameReplacement: ''
                    layout:
                      mobileThresholdPx: 500 # Default is 650
                      groups: 
                        width: '35%' # Default 25%
                        mobileWidth: '20%' # Default 100%
                      players:
                        width: '100%' # Default 25%
                        mobileWidth: '80%' # Default 100%
                      favorites:
                        width: '80%' # Default 33%
                        mobileWidth: '80%' # Default 100%
                      favorite:
                        width: '25%' # Default 33%
                        mobileWidth: '25%' # Default 16%
            template:
              - media
              - icon_sonos_one
```

But it seems every cards in this section don't have hold action available...

**Comment by matt8707** [comment]
I have no idea, this works on my end

```yaml
type: custom:button-card
entity: sensor.plex_recently_added
name: Senast tillagt
tap_action:
  action: none
template:
  - conditional_media
  - icon_plex
hold_action:
  !include popup/studio_flakt.yaml
```
