### ISSUE TITLE
Unknown type encountered: image.

### ISSUE THREAD

**Issue by JorgeAnzola** [matt8707/hass-config#6]
This is the best repo ever. I'm trying to copy so many things, but I'm a big noob, so maybe the question is stupid. I'm first trying with a fan. But I cannot find the "image" card. 

I've done: 

```
    resources:
      - type: js
        url: /community_plugin/rgb-light-card/card.js
      - type: js
        url: /community_plugin/state-element/state-element.js
    title: Home
    views:
      - badges: []
        cards:
          - entity: switch.plug_1
            state_image:
              'off': /local/images/fan_off.gif
              'on': /local/images/fan_on.gif
              unavailable: /local/unknown.png
            style:
              left: 80.05%
              top: 37.9%
              width: 10%
            tap_action:
              action: toggle
            title: null
            type: image
```

But I keep getting `Unknown type encountered: image.` solid start. I cannot find an image in HACS or the add-ons. What are you using there?

Thanks a lot!
