### ISSUE TITLE
[FR] Countdown on items like HVAC

### ISSUE THREAD

**Issue by icodesdeveloper** [matt8707/hass-config#66]
A great addition would be to implement a countdown timer in the popups for things like the HVAC.

**Comment by matt8707** [comment]
Good idea! How should it work? I came up with this

<img width="449" alt="screen" src="https://user-images.githubusercontent.com/36163594/170886785-e658e7a4-6f44-462e-a14e-527482873622.png">


```yaml
timer:
  climate:
    name: Countdown
    icon: mdi:timer-outline

input_number:
  climate_timer:
    name: Shutdown time
    icon: mdi:timer-outline
    initial: 4
    min: 1
    max: 12
    unit_of_measurement: h

switch:
  - platform: template
    switches:
      climate_timer:
        friendly_name: State
        icon_template: mdi:timer-outline
        value_template: >
          {{ is_state('timer.climate', 'active') }}
        turn_on:
          service: timer.start
          target:
            entity_id: timer.climate
          data:
            duration: >
              {{ states('input_number.climate_timer') | int(0) * 3600 }}
        turn_off:
          service: timer.cancel
          target:
            entity_id: timer.climate

automation:
  - alias: climate_timer
    id: '3683394346277'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.climate
    action:
      service: climate.turn_off
      target:
        entity_id: climate.ac
```

popup

```yaml
- type: entities
  entities:
    - type: custom:slider-entity-row
      entity: input_number.climate_timer
      hide_state: false
    - entity: switch.climate_timer
    - entity: timer.climate
```

**Comment by icodesdeveloper** [comment]
Wow i forgot this already, very busy in my last year secundairy school.
Maybe now searching a fancyer slider that fits more in the ui and thats finished!

**Comment by icodesdeveloper** [comment]
A few hours is also way too long, it is much better per quarter hour.

I changed the timer to this:

```
  climate_bureau:
    name: Shutdown time
    icon: mdi:timer-outline
    initial: 0.25
    min: 0.25
    max: 6
    step: 0.25
    unit_of_measurement: h
```


Also for working per quarter hours you cant use an int so we need a float

`- platform: template
  switches:
    climate_woonkeuken:
      friendly_name: Status
      icon_template: mdi:timer-outline
      value_template: >
        {{ is_state('timer.climate_woonkeuken', 'active') }}
      turn_on:
        service: timer.start
        target:
          entity_id: timer.climate_woonkeuken
        data:
          duration: >
            {{ states('input_number.climate_woonkeuken') | float * 3600 }}
      turn_off:
        service: timer.cancel
        target:
          entity_id: timer.climate_woonkeuken
`



Now it shows as small tip in the slider as .25 hours it would be better if we can change that it for example 01.00, 01.15, 01.45, 45m
![image](https://user-images.githubusercontent.com/57155890/172721438-cf507c21-fb04-4088-b68c-bff8587dea39.png)
