### ISSUE TITLE
Music Assistant

### ISSUE THREAD

**Issue by Backslashh** [matt8707/hass-config#69]
With Music Assistant now released, would we be able to integrate this somehow within the dashboard? It's currently a separate panel which makes it tricky and an iFrame may be a little too clunky.

Thoughts on this one?

**Comment by matt8707** [comment]
If you don't want to navigate I think an iframe is ok

![ma](https://user-images.githubusercontent.com/36163594/174724076-e02e0cd7-c311-4385-b4eb-f233cf259bf9.jpg)

```yaml
- type: custom:button-card
  name: >
    <ha-icon icon="mdi:music-circle-outline"></ha-icon> Music
  tap_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      title: Music Assistant
      style:
        div: |
          .content {
            padding: 0;
          }
        hui-iframe-card$: |
          ha-card {
            margin-left: -58px;
          }
      large: true
      card:
        type: iframe
        url: >
          [[[ return `/${hass.panels["media-browser"].url_path}` ]]]
  template: footer
```

[same as hacs popup](https://github.com/matt8707/hass-config/blob/a2750482d076fbd96c5cb3415b45b2763d7ba04e/button_card_templates.yaml#L773-L802)
