### ISSUE TITLE
Question about person location update

### ISSUE THREAD

**Issue by davidepanato** [matt8707/hass-config#74]
Hello mattias,
  thanks for your good work!
I'm using it as a baseline for my dashboard and I have a question. Person card uses a sensor (sensor.matte_last_changed) to track last location change.
I have seen in the code that you're managing it through MQTT. Have you done it to keep value even if HA restarts? How do you publish the value on the topic?

Thanks a lot!
Davide

**Comment by Backslashh** [comment]
Hi Davide,
Yep - that sensor is purely for presence persistence across reboots. That way it can accurately tell you how long the person has been in a specific state.

When the users state changes, an MQTT call is made to publish the new timestamp for that user.
Here's mine from my automation.yaml
```
- alias: person_home
    id: "8423590985012"
    mode: parallel
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - person.user1
          - person.user2
        from:
          - home
          - not_home
        to:
          - home
          - not_home
    action:
      service: mqtt.publish
      data:
        topic_template:
          "homeassistant/persistence/{{ trigger.to_state.name | lower }}

          "
        payload_template: "{{ now() }}

          "
        retain: true
```
